# Generated by Django 5.0.3 on 2024-03-22 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0002_initial'),
        ('student_app', '0005_remove_student_personal_email_and_more'),
        ('subject_app', '0002_remove_subject_students_alter_subject_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='a_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='subject_app.subject'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student_app.student'),
        ),
    ]
