# Generated by Django 5.0.3 on 2024-03-22 20:31

import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_student_subjects_alter_student_locker_combination_and_more'),
        ('subject_app', '0002_remove_subject_students_alter_subject_professor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='personal_email',
        ),
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='12-12-12', max_length=255, validators=[student_app.validators.validate_combination_format]),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='subject_app.subject'),
        ),
    ]
